"""
Autonomous Rubric Evolution Engine — iterative improvement via DeepSeek API.

Uses cached test set responses (no GPU needed). Each round:
1. Score sample responses with each rubric (individual scoring)
2. Analyze: parse rate, score differentiation, domain coverage
3. For problematic rubrics, ask DeepSeek (thinking=enabled) to rewrite
4. Verify improvement, iterate until convergence

Usage: python tmp/evolve_rubrics.py [--max-rounds 5] [--keep-best]
"""
import json
import os
import sys
import time
import hashlib
import argparse

API_KEY = os.environ.get("DEEPSEEK_API_KEY", "sk-906ad0dc48354e7aba594ef6d9aa5be6")
BASE_URL = "https://api.deepseek.com"
MODEL = "deepseek-v4-flash"

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from openai import OpenAI
from trainable_openclaw.evaluation.judge import JudgeExecutor
from trainable_openclaw.evaluation.rubric import Rubric

client = OpenAI(api_key=API_KEY, base_url=BASE_URL)

# ---- Helpers ----

def load_cached_responses(path="data/coding/testset_eval.json"):
    """Load cached test set responses (pre-generated by eval_testset.py)."""
    import re
    with open(path, "r", encoding="utf-8") as f:
        data = json.load(f)
    samples = []
    for r in data["results"]:
        resp = r.get("full_response", "")
        # Remove ALL <think>...</think> blocks (they may appear anywhere)
        code = re.sub(r'<think>.*?</think>', '', resp, flags=re.DOTALL).strip()
        if not code:
            code = resp  # fallback: use full response if nothing left
        if code.strip():
            samples.append({
                "prompt": r["prompt"],
                "code": code,
                "code_len": len(code),
            })
    return samples


def load_rubrics(path="data/coding_debug/rubrics_v2.json"):
    with open(path, "r", encoding="utf-8") as f:
        data = json.load(f)
    return [Rubric.from_dict(d) for d in data]


def score_rubric(rubric, samples, judge):
    """Score one rubric against N samples. Returns parse rate + score stats."""
    scores = []
    parse_ok = 0
    parse_fail = 0

    for s in samples:
        result = judge.score_one_sync(rubric, s["code"])
        scores.append(result.分数)
        if result.解析错误:
            parse_fail += 1
        else:
            parse_ok += 1

    return {
        "scores": scores,
        "parse_ok": parse_ok,
        "parse_fail": parse_fail,
        "parse_rate": parse_ok / len(samples) if samples else 0,
        "mean": sum(scores) / len(scores) if scores else 0,
        "min": min(scores) if scores else 0,
        "max": max(scores) if scores else 0,
        "nonzero_rate": sum(1 for s in scores if s > 0) / len(scores) if samples else 0,
    }


def analyze_rubric(rubric, stats, sample_codes):
    """Analyze rubric quality and generate improvement suggestions."""
    issues = []

    if stats["parse_rate"] < 0.7:
        issues.append(f"JSON parse rate too low ({stats['parse_rate']:.0%})")
    if stats["nonzero_rate"] < 0.3:
        issues.append(f"Scores almost all zero ({stats['nonzero_rate']:.0%} non-zero) — criteria too narrow or strict")
    if stats["max"] - stats["min"] < 3:
        issues.append(f"Low differentiation (range {stats['min']}-{stats['max']})")
    if stats["mean"] < 1:
        issues.append(f"Mean too low ({stats['mean']:.1f}) — rubric too strict")
    if stats["mean"] > 8:
        issues.append(f"Mean too high ({stats['mean']:.1f}) — rubric too lenient")

    return issues


def generate_improved_rubric(rubric, stats, sample_codes, sample_scores, issues):
    """Ask DeepSeek (with thinking) to rewrite a rubric for better quality."""
    code_examples = []
    for i, (code, score) in enumerate(zip(sample_codes[:4], sample_scores[:4])):
        code_examples.append(f"--- Example {i+1} (current score: {score:.0f}/10) ---\n{code[:600]}")

    examples_text = "\n\n".join(code_examples)
    issues_text = "\n".join(f"- {i}" for i in issues)

    prompt = f"""You are a code review rubric designer. Your job is to rewrite a rubric to be more effective for evaluating AI-generated code.

CURRENT RUBRIC:
Name: {rubric.名称}
Scoring Prompt:
{rubric.评分提示词}

PROBLEMS WITH THIS RUBRIC:
{issues_text}

SCORING STATISTICS (on {len(sample_scores)} code samples):
- Mean: {stats['mean']:.1f}/10
- Range: {stats['min']:.0f}-{stats['max']:.0f}/10
- Parse success rate: {stats['parse_rate']:.0%}
- Non-zero rate: {stats['nonzero_rate']:.0%}

SAMPLE CODE + SCORES:
{examples_text}

INSTRUCTIONS:
Rewrite this rubric to fix the problems above. Requirements:
1. Criteria must be GENERAL — work across Python, JavaScript, TypeScript, C, SQL, Rust, Swift, etc. NO language-specific API checks.
2. Scoring must be GRANULAR — differentiate poor (0-3), acceptable (4-6), good (7-8), excellent (9-10) code.
3. JSON output format must be STRICT. Every response MUST start with {{"分数": followed by a 0-10 integer.
4. The rubric should focus on one clear dimension of code quality.
5. The scoring prompt MUST contain the exact placeholder string {{content}} (literally these 9 characters) where code will be inserted.
6. Keep the rubric concise — under 600 characters total.
7. IMPORTANT: The scoring criteria must be GENERAL, not tied to any specific language, framework, or use case (no PLC, SQL, Node.js, etc. specific checks).

Output ONLY the improved rubric as a JSON array with one element:
[{{"名称": "Dimension Name", "评分提示词": "Full scoring prompt with {{content}} placeholder + JSON output format instruction"}}]

Reply ONLY with the JSON array, no other text."""

    print(f"  Asking DeepSeek to rewrite '{rubric.名称}'...")

    resp = client.chat.completions.create(
        model=MODEL,
        messages=[{"role": "user", "content": prompt}],
        temperature=0.7,
        max_tokens=4000,
        extra_body={"thinking": {"type": "enabled"}},
    )
    raw = resp.choices[0].message.content.strip()
    # Extract JSON from response
    if raw.startswith("```"):
        raw = raw.split("\n", 1)[1].rsplit("```", 1)[0].strip()
    # Try to find JSON array/object bounds
    if not raw.startswith("["):
        # Find first [ or {
        for start_char, end_char in [("[", "]"), ("{", "}")]:
            si = raw.find(start_char)
            if si >= 0:
                ei = raw.rfind(end_char)
                if ei > si:
                    raw = raw[si:ei+1]
                    break
    try:
        new_rubrics = json.loads(raw)
        if isinstance(new_rubrics, list) and len(new_rubrics) > 0:
            result = new_rubrics[0]
        elif isinstance(new_rubrics, dict):
            result = new_rubrics
        else:
            return None
        # Fill required fields
        if "名称" in result and "评分提示词" in result:
            result.setdefault("id", hashlib.md5(result["名称"].encode()).hexdigest()[:12])
            result.setdefault("来源模式", "evolved")
            return result
    except json.JSONDecodeError:
        print(f"  ERROR: Failed to parse LLM output as JSON: {raw[:300]}")
    return None


def save_rubrics(rubrics, path, version):
    """Save rubrics to JSON file."""
    output = []
    for i, r in enumerate(rubrics):
        rid = hashlib.md5(f"{r.名称}_{version}_{i}".encode()).hexdigest()[:12]
        output.append({
            "id": rid,
            "名称": r.名称,
            "评分提示词": r.评分提示词,
            "来源模式": f"evolved_v{version}",
            "版本": version,
            "命中次数": 0,
            "最后命中时间": 0.0,
            "状态": "活跃",
            "创建时间": time.time(),
            "适用类别": ["coding"],
        })
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(output, f, ensure_ascii=False, indent=2)
    return path


# ---- Main ----

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--max-rounds", type=int, default=5)
    parser.add_argument("--keep-best", action="store_true", help="Always keep best version of each rubric")
    parser.add_argument("--eval-samples", type=int, default=8, help="Samples per rubric for evaluation")
    args = parser.parse_args()

    # Load cached test set responses
    print("=" * 60)
    print("RUBRIC EVOLUTION ENGINE")
    print("=" * 60)

    testset_paths = ["data/coding/testset_eval.json", "data/coding_debug/testset_eval.json"]
    samples = []
    for p in testset_paths:
        try:
            samples = load_cached_responses(p)
            print(f"Loaded {len(samples)} cached test responses from {p}")
            break
        except FileNotFoundError:
            continue
    if not samples:
        print("ERROR: No cached test responses found. Run eval_testset.py first.")
        return

    # Load current rubrics
    rubrics_path = "data/coding_debug/rubrics_v2.json"
    rubrics = load_rubrics(rubrics_path)
    print(f"Loaded {len(rubrics)} seed rubrics from {rubrics_path}")
    for r in rubrics:
        print(f"  - {r.名称} ({len(r.评分提示词)} chars)")

    # Use subset of samples for evaluation
    eval_samples = samples[:min(args.eval_samples, len(samples))]
    print(f"\nEvaluation set: {len(eval_samples)} code samples (avg {sum(s['code_len'] for s in eval_samples)//len(eval_samples)} chars)")

    judge = JudgeExecutor(
        api_key=API_KEY, base_url=BASE_URL, model=MODEL,
        enable_thinking=False, use_merged=False,
    )

    best_rubrics = list(rubrics)
    best_score = -1
    version = 0

    for round_num in range(1, args.max_rounds + 1):
        print(f"\n{'=' * 60}")
        print(f"ROUND {round_num}/{args.max_rounds}")
        print(f"{'=' * 60}")

        all_stats = []
        for i, rubric in enumerate(rubrics):
            print(f"\n  Rubric {i+1}: {rubric.名称}")
            t0 = time.time()
            stats = score_rubric(rubric, eval_samples, judge)
            all_stats.append(stats)
            elapsed = time.time() - t0
            print(f"    Parse: {stats['parse_rate']:.0%} | Mean: {stats['mean']:.1f} | Range: {stats['min']:.0f}-{stats['max']:.0f} | NonZero: {stats['nonzero_rate']:.0%} | {elapsed:.1f}s")

        # Aggregate quality score
        parse_rates = [s["parse_rate"] for s in all_stats]
        score_ranges = [s["max"] - s["min"] for s in all_stats]
        overall = sum(parse_rates) / 4 * 50 + sum(score_ranges) / 4 * 5
        print(f"\n  OVERALL: parse_rate={sum(parse_rates)/4:.1%} range_avg={sum(score_ranges)/4:.1f} quality={overall:.1f}")

        if overall > best_score:
            best_score = overall
            best_rubrics = list(rubrics)
            version += 1
            save_rubrics(best_rubrics, f"data/coding_debug/rubrics_evolved_v{version}.json", version)
            print(f"  => Saved best rubrics (v{version})")

        # Check convergence
        issues_found = 0
        for i, (rubric, stats) in enumerate(zip(rubrics, all_stats)):
            issues = analyze_rubric(rubric, stats, [s["code"] for s in eval_samples])
            if issues:
                issues_found += len(issues)
                print(f"\n  Issues with '{rubric.名称}':")
                for issue in issues:
                    print(f"    - {issue}")

        if issues_found == 0:
            print(f"\n=== CONVERGED at round {round_num} — all rubrics healthy! ===")
            break

        # Evolve problematic rubrics
        problematic_count = sum(1 for i, s in enumerate(all_stats)
                               if analyze_rubric(rubrics[i], s, [c["code"] for c in eval_samples]))
        print(f"\n--- Evolving {problematic_count} problematic rubrics ---")

        new_rubrics = list(rubrics)
        for i, (rubric, stats) in enumerate(zip(rubrics, all_stats)):
            issues = analyze_rubric(rubric, stats, [s["code"] for s in eval_samples])
            if not issues:
                continue

            improved = generate_improved_rubric(
                rubric, stats,
                [s["code"] for s in eval_samples],
                stats["scores"],
                issues,
            )
            if improved and improved.get("名称") and improved.get("评分提示词"):
                r = Rubric.from_dict(improved)
                new_rubrics[i] = r
                print(f"  => Improved: {r.名称} ({len(r.评分提示词)} chars)")
            else:
                print(f"  => Failed to improve '{rubric.名称}', keeping original")

        rubrics = new_rubrics
        time.sleep(2)  # Rate limit

    # Save final version
    final_path = "data/coding_debug/rubrics_evolved_final.json"
    save_rubrics(rubrics, final_path, version + 1)
    print(f"\n=== Final rubrics saved to {final_path} ===")

    # Print final stats
    print("\nFINAL RUBRICS:")
    for i, r in enumerate(rubrics):
        print(f"\n  {r.名称} ({len(r.评分提示词)} chars)")
        print(f"  {r.评分提示词[:300]}...")


if __name__ == "__main__":
    main()
